<?php
include('../inc/dbconnect.php');
session_start();
$username = $_SESSION['username'];

$sql = "SELECT * FROM staff WHERE username = '".$username."'";
$result = $conn->query($sql);
$row = $result->fetch_assoc();

$sqlEmail = "SELECT email from admin WHERE username = 'adminrory'";
$resultEmail = $conn->query($sqlEmail);
$rowEmail = $resultEmail->fetch_assoc();

$email = $rowEmail['email'];


if(isset($_POST['submit'])){
	$ic = strtoupper($_POST['ic']);
	$date = $_POST['traveldate'];
}


?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="../css/permit.css">
	<title>Print - Work Travel Permit</title>
</head>
<body onload="window.print()">
	<div class="companyheading">
		<center>
			<img src="../imgsource/basic/logo.png" height="70px" width="140px">
			<br>BOOK4U STORE
		</center>
	</div>
	<hr>
	
	<div class="innerletter"><span id="printid"><button onclick="window.print()">print</button></span>
		NAME: <?php echo $row['name'] ?><br>
		No. KP: <?php echo $ic ?><br>
		DATE: <?php echo strtoupper(date('d F Y', strtotime($date))); ?>
		<div class="recipientheading">
			POLIS DIRAJA MALAYSIA<br>WILAYAH PERSEKUTUAN KUALA LUMPUR.
		</div>
		Sir/ Madam,

		<div class="title">
			SUBJECT: TRAVEL PERMIT AUTHORIZATION LETTER FOR STAFF ON DUTY OF ESSENTIAL SERVICE.
		</div>

		Referring to the matter above, our company verifies the relevant personnel mentioned above is our company's employee permitted to perform required travel for purposes of performing official duty and entering premises in order to provide essential services. The address of company is as stated below:<br><br>

		<b>9G, Jalan Layang SB 9/3,<br>Taman Sungai Besi,<br>43300 Seri Kembangan, Selangor</b><br><br>
		
		Therefore, it is greatly appreciated for the Covid-19 enforcement officer to allow the employee reporting her/ his duty in this Covid-19 order implementation.<br><br>

		Do not hesitate to contact our officer from Human Resources Department for any inquiries.<br>
		<center><b>HR Officer: Rory Aminah 03-33229921</b></center><br><br>

		Your kind cooperation is greatly appreciated.<br><br>

		Thank you.<br>
		Sincerely,<br>
		<img src="../imgsource/basic/sign.png" height="60px" width="120px"><br>
		NURUL AIN FATEHAH<br>
		9G, Jalan Layang SB 9/3,<br>Taman Sungai Besi,<br>43300 Seri Kembangan, Selangor<br>
		tel: 03-42992283

	</div>

	<?php

	require_once '../vendor/autoload.php';
				//create transport
		$transport = (new Swift_SmtpTransport('smtp.gmail.com', 587, 'tls'))
		->setUsername("notify.sbppp@gmail.com")
		->setPassword("SBPPP2020");

				// Create the Mailer using your created Transport
		$mailer = new Swift_Mailer($transport);

				// Create a message
		$message = new Swift_Message();	
		$message->setSubject('[BOOK4U] Travel Permit Was Generated by '.$row["name"]);
		$message->setFrom(['notify.sbppp@gmail.com' => 'BOOK4U Store Notification']);
		$message->setTo($email);
		$message->setBody('<html>' .
			'<body>' .
			'<div style="font-size: 14px; font-family: sans-serif; text-align: justify;">'.
			'Hello, ADMINRORY' . 
			'<br><br>'.
			'Please be informed that staff <b>'.$row["name"].'</b> with IC/ passport no. <b>' . $ic . '</b> had just exported a work travel permit letter for the date <b>'. strtoupper(date('d F Y', strtotime($date))) .
			'</b><br><br>This confirmation e-mail serves purpose to avoid staff from using work privilege for personal matter.'.
			'<br><br>'.			
			'<table border="0" width="70%" text-align="center">'.					
			'<tr>'.
			'<th>'.
			'<div style="font-family: sans-serif; font-size: 14px; text-align: left">'.
			'	Date '.
			'</div>'.
			'</th>'.
			'<td>'.
			':'.
			'</td>'.
			'<td>'.
			'<div style="font-family: sans-serif; font-size: 14px; padding-left: 25px; text-align: left">'.
			'	'. $date .' '.
			'</div>'.
			'</td>'.
			'</tr>'.
			'<tr>'.
			'<th>'.
			'<div style="font-family: sans-serif; font-size: 14px; text-align: left; text-align: left">'.
			'	Time '.
			'</div>'.
			'</th>'.
			'<td>'.
			':'.
			'</td>'.
			'<td>'.
			'<div style="font-family: sans-serif; font-size: 14px; padding-left: 25px">'.
			'	'.date("H:i A", time()+25200).' '.
			'</div>'.
			'</td>'.
			'</tr>'.
			'</table>'.
			'</div>'.
			'<br><br>'.
			'<div style="font-size: 14px; font-family: sans-serif; text-align: justify;">'.
			'To visit the Book4U Store, please go to <a href="https://webapp.utem.edu.my/student/bitd/b032020035/BOOK4UStore/" style="color: blue">https://webapp.utem.edu.my/student/bitd/b032020035/BOOK4UStore/</a>.<br><br>Thank you and have a good day ahead!.'.
			'</div>'.
			'</div>'.
			'<br>'.
			'<div style="text-align: center; color: gray; font-size: 14px; font-family: sans-serif;">'.
			'<hr>'.
			'	This is an auto-generated email. Please do not reply to this email. '.
			'</div>'.
			'</body>' .
			'</html>',
			'text/html'
		);

						//send the email

		$result = $mailer->send($message);


	?>
</body>
</html>